### ISSUE TITLE
programmatic access to mapper

### ISSUE THREAD

**Issue by isthisthat** [ISA-tools/ISAcreator#189]
Hello,
I was wondering whether the mapper could be called programmatically. For example as:

```
ISAcreator --map myAttributes.txt --mappings attribute_mappings.xml --output /path/to/output/ISA-archive --config isaconfig-xxx
```

I would have liked to contribute this but it would be _a lot_ of work for a non expert (non expert in ISA-tab and java). Especially because of the fact that it requires a configuration to be loaded (rather than just using the mappings, which are not saved in ISA-tab order!). I toyed around with the python library but that is suited for reading and not for writing/creating ISA-tab from scratch..

Hope that a programmatic API will be considered in the future.

**Comment by agbeltran** [comment]
This functionality will be considered as part of the ISA-API (https://github.com/ISA-tools/isa-api/issues/167)
