### ISSUE TITLE
Publication auto-fill does not work if any cell is non-empty

### ISSUE THREAD

**Issue by ghost** [ISA-tools/ISAcreator#208]
In the Study Publications section, after searching for a publication by DOI or PubMed ID, the "select publication" button should auto-fill the Study\* fields in the publication column. 

This fails silently if there is any text in any of the existing fields. I suggest allowing existing text to be overwritten, but with a warning if this is going to happen.

**Comment by sneumann** [comment]
This is still/again present in the 1.7.8 distributed by the MetaboLights team.

**Comment by sneumann** [comment]
Ken checked, and it seems to work. I'll have to re-check with a clean install

**Comment by khaug** [comment]
Testing with 1.7.8 and preliminary conclusion is that it adds new publications using both PMID and DOI, but does not overwrite existing entry (or add same publication twice).  DOI field does not accept the "doi:" prefix
