### ISSUE TITLE
Create isacreator.jar without bundled dependencies

### ISSUE THREAD

**Issue by timeu** [ISA-tools/ISAcreator#285]
Both JARs (**isacreator.jar** and **isacreator-with-depdencencies.jar**) contain all its maven dependencies (i..e `javax.persistence`, etc).
Even when I exclude dependencies in my application `pom.xml` file, the corresponding classes still will be picked up by the classloader. 

For example in my application I use `JPA2`, but the **isacreator.jar** contains `JPA1` classes and I get `ClassNotFoundException` even tough I excluded the corresponding maven depenceny (both JPA1 and JPA2 classes are in the classpath). 

Solution: Create a jar package that doesn't contain any dependencies

**Comment by djcomlab** [comment]
This was a release issue, we can provide the no-deps .jar in the upcoming 1.7.10 release. Closing.
