### ISSUE TITLE
Export only a subset of assays to ISAarchive.zip

### ISSUE THREAD

**Issue by sneumann** [ISA-tools/ISAcreator#291]
Hi,

if I have a multi-omics study, ISAcreator is intended to provide submissions 
to the individual omics-specific repositories, like Pride or ArrayExpress
using the "convert ISAtab" export function, where I can even specify 
which assays to include. 

What's missing is a selective export of assays to _ISAtab_, which is required 
e.g. if I submit to MetaboLights, and want to only include the metabolite profiling assays, 
and skip the transcription profiling assays. See MTBLS18 at 
http://www.ebi.ac.uk/metabolights/reviewerwIP6uotGKX 
for an example that still includes a_ipb-2014-01_transcription profiling_DNA microarray.txt 
in the i_Investigation. Optionally don't zip up the files and protocols referenced 
from the exluded assays.

Clearly, this is a wishlist item :-) 

Yours,
Steffen

**Comment by agbeltran** [comment]
This functionality has been implemented in the [ISA-API](http://github.com/ISA-tools/isa-api) and we will close this issue in ISAcreator.
