### ISSUE TITLE
Cannot build from source, cannot run the precompiled binary

### ISSUE THREAD

**Issue by childers** [ISA-tools/ISAcreator#296]
I was trying to use ISACreator, and have not been able to get it to build or run on my system (OSX10.10.1).  When I try to build the project I get the following output below.  I also tried downloading the precompiled tool directly from the project page (http://isatab.sourceforge.net/tools.html) but the ISACreator would not run directly. I was able to use the CLI command to start it up after navigating to the jar file.

$ mvn assembly:assembly -Dmaven.test.skip=true -Pbuild
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.isatools:ISAcreator:bundle:1.7.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 146, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ISAcreator 1.7.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-assembly-plugin:2.4:assembly (default-cli) > package @ ISAcreator >>>
[WARNING] The POM for xalan:xalan:jar:2.4 is missing, no dependency information available
[WARNING] The POM for org.codehaus.jackson:jackson-core-asl:jar:1.7.0-SNAPSHOT-20101126.221009-1 is missing, no dependency information available
[INFO] 
[INFO] --- xmlbeans-maven-plugin:2.3.3:xmlbeans (default) @ ISAcreator ---
[INFO] All schema objects are up to date.
[INFO] 
[INFO] --- jaxws-maven-plugin:2.2:wsimport (default) @ ISAcreator ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ISAcreator ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 26 resources
[INFO] Copying 666 resources
[INFO] Copying 2672 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ ISAcreator ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 315 source files to /Users/user1/git-repositories/ISAcreator/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] bootstrap class path not set in conjunction with -source 1.5
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/validateconvert/ui/ENASubmissionUI.java:[4,18] AWTUtilities is internal proprietary API and may be removed in a future release
[WARNING] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/validateconvert/ui/ValidateUI.java:[40,18] AWTUtilities is internal proprietary API and may be removed in a future release
[WARNING] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/gui/modeselection/ModeSelector.java:[39,18] AWTUtilities is internal proprietary API and may be removed in a future release
[WARNING]  A web service endpoint could not be found
6 warnings
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/validateconvert/ui/ENASubmissionUI.java:[4,18] AWTUtilities is internal proprietary API and may be removed in a future release
[WARNING]  class CiteExploreClient
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/validateconvert/ui/ValidateUI.java:[40,18] AWTUtilities is internal proprietary API and may be removed in a future release
[WARNING] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/gui/modeselection/ModeSelector.java:[39,18] AWTUtilities is internal proprietary API and may be removed in a future release
[WARNING] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/validateconvert/ui/ENASubmissionUI.java:[87,12] AWTUtilities is internal proprietary API and may be removed in a future release
[WARNING]  class CiteExploreClient
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/validateconvert/ui/ValidateUI.java:[105,12] AWTUtilities is internal proprietary API and may be removed in a future release
[WARNING] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/gui/modeselection/ModeSelector.java:[91,8] AWTUtilities is internal proprietary API and may be removed in a future release
[INFO] 9 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[58,12] error: cannot find symbol
[ERROR]  class CiteExploreClient
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[88,104] error: cannot find symbol
[ERROR]  class CiteExploreClient
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[95,106] error: cannot find symbol
[ERROR]  class CiteExploreClient
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[107,53] error: cannot find symbol
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/validateconvert/ui/ENASubmissionUI.java:[78,56] error: reference to inject is ambiguous, both method inject(Object...) in ResourceInjector and method inject(boolean,Object...) in ResourceInjector match
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[61,22] error: cannot find symbol
[ERROR]  class CiteExploreClient
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[81,17] error: cannot find symbol
[ERROR]  class CiteExploreClient
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[96,8] error: cannot find symbol
[ERROR]  class CiteExploreClient
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[98,8] error: cannot find symbol
[ERROR]  class CiteExploreClient
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[99,8] error: cannot find symbol
[ERROR]  class CiteExploreClient
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[110,13] error: cannot find symbol
[ERROR]  class CiteExploreClient
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[112,13] error: cannot find symbol
[ERROR]  class CiteExploreClient
/Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[120,21] error: cannot find symbol
[INFO] 13 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.550 s
[INFO] Finished at: 2015-01-22T12:37:50-05:00
[INFO] Final Memory: 12M/311M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project ISAcreator: Compilation failure: Compilation failure:
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[58,12] error: cannot find symbol
[ERROR] class CiteExploreClient
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[88,104] error: cannot find symbol
[ERROR] class CiteExploreClient
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[95,106] error: cannot find symbol
[ERROR] class CiteExploreClient
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[107,53] error: cannot find symbol
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/validateconvert/ui/ENASubmissionUI.java:[78,56] error: reference to inject is ambiguous, both method inject(Object...) in ResourceInjector and method inject(boolean,Object...) in ResourceInjector match
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[61,22] error: cannot find symbol
[ERROR] class CiteExploreClient
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[81,17] error: cannot find symbol
[ERROR] class CiteExploreClient
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[96,8] error: cannot find symbol
[ERROR] class CiteExploreClient
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[98,8] error: cannot find symbol
[ERROR] class CiteExploreClient
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[99,8] error: cannot find symbol
[ERROR] class CiteExploreClient
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[110,13] error: cannot find symbol
[ERROR] class CiteExploreClient
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[112,13] error: cannot find symbol
[ERROR] class CiteExploreClient
[ERROR] /Users/user1/git-repositories/ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java:[120,21] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by agbeltran** [comment]
Hi,

Maven 2.2.1 is required to build ISAcreator. Could you please check what maven version you have installed?

Also, please let me know what Java version you are using.

Thanks

**Comment by childers** [comment]
Hi,
I am running Maven 3.2.3, and Java 1.7.  
...
$ mvn -v 
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T16:58:10-04:00)
Maven home: /usr/local/Cellar/maven/3.2.3/libexec
Java version: 1.7.0_65, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"

**Comment by agbeltran** [comment]
Java 1.7 should be ok (except one minor change in a class, as reported in #290), but you will have to install maven 2.2.1 (as after version 3, support for profiles.xml was removed). Let us know how you get on and if you find any other issue. Thanks.

**Comment by agbeltran** [comment]
Hi @childers 
I was wondering if you had any success compiling ISAcreator? I have just pushed an update related to the CiteExplore service that might have been related to the problem you were having.
It would be great if you could try compiling again (from the development branch) and let me know how you get on. 
Also, your issue mentioned that you couldn't run the jar, was that the 1.7.8-prerelease? 
Thanks

**Comment by childers** [comment]
Hi @agbeltran, sorry for the huge delay in replying.  I just did a pull on the development branch and it comiles and runs now.  I have not had time to do much more than test that it is running, but it looks great so far!

Chris

**Comment by agbeltran** [comment]
That's great, Chris. I guess we can close this issue now? Or let us know if there are more problems.

**Comment by childers** [comment]
Yes please feel free to close.  Thank you for your patience!

Chris
