### ISSUE TITLE
After creating ISAarchive.zip, ISAcreator process hogs 100% CPU

### ISSUE THREAD

**Issue by sneumann** [ISA-tools/ISAcreator#297]
Hi, subject says all, I can continue to work normally in ISAcreator, 
but something is happening in a background thread, heating CPU and my knees. 

This has happened through several linux/java/ISAcreator installations I had over the years,
including OpenJDK/Sun/Oracle under Ubuntu 12.04 and 14.04.
Any idea what I should try to hunt this down ?

**Comment by sneumann** [comment]
This seems to be fixed with 
```
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by agbeltran** [comment]
thanks for checking @sneumann
