### ISSUE TITLE
v1.7.7 doesn't work in OS X 10.8.5

### ISSUE THREAD

**Issue by flekschas** [ISA-tools/ISAcreator#302]
After moving the folder containing the app and app related data to /Applications and double clicking on the app, OS X tells me that the app is damaged and can't run.

**Comment by eamonnmag** [comment]
Hi Fritz, 

You need to change your security settings on mac. See here - http://www.isa-tools.org/running-isa-tools-in-mountain-lion/

**Comment by flekschas** [comment]
Great thanks, its working now!

**Comment by eamonnmag** [comment]
Great! :)
