### ISSUE TITLE
NullPointerException when doing ORCID lookup

### ISSUE THREAD

**Issue by chrisfilo** [ISA-tools/ISAcreator#304]
ISACreator 1.7.7
Java 1.8.0

Steps to replicate:
1. Open ISACreator
2. Create a new account
3. Orcid look up
4. Type in a query

```
starting search
query string=q=text:gorgolewski
URI=http://pub.orcid.org/search/orcid-bio/?q=text:gorgolewski
status text=OK
contents=<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<orcid-message xmlns="http://www.orcid.org/ns/orcid">
    <message-version>1.1</message-version>
    <orcid-search-results num-found="20">
        <orcid-search-result>
            <relevancy-score>0.8385465</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0003-3321-7583</uri>
                    <path>0000-0003-3321-7583</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Krzysztof</given-names>
                        <family-name visibility="public">Gorgolewski</family-name>
                        <credit-name visibility="public">Krzysztof Jacek Gorgolewski</credit-name>
                        <other-names visibility="public">
                            <other-name>Chris Filo Gorgolewski</other-name>
                        </other-names>
                    </personal-details>
                    <researcher-urls visibility="public">
                        <researcher-url>
                            <url-name>Personal Blog</url-name>
                            <url>http://multiplecomparisons.blogspot.com</url>
                        </researcher-url>
                    </researcher-urls>
                    <contact-details>
                        <address>
                            <country visibility="public">US</country>
                        </address>
                    </contact-details>
                    <keywords visibility="public">
                        <keyword>neuroimaging</keyword>
                        <keyword>neuroinformatics</keyword>
                    </keywords>
                    <external-identifiers visibility="public">
                        <external-identifier>
                            <external-id-common-name>Loop profile</external-id-common-name>
                            <external-id-reference>34684</external-id-reference>
                            <external-id-url>http://loop.frontiersin.org/people/34684/overview?referrer=orcid_profile</external-id-url>
                        </external-identifier>
                        <external-identifier>
                            <external-id-common-name>Scopus Author ID</external-id-common-name>
                            <external-id-reference>55355064700</external-id-reference>
                            <external-id-url>http://www.scopus.com/inward/authorDetails.url?authorID=55355064700&amp;partnerID=MN8TOARS</external-id-url>
                            <external-id-source>
                                <uri>http://orcid.org/0000-0002-5982-8983</uri>
                                <path>0000-0002-5982-8983</path>
                                <host>orcid.org</host>
                            </external-id-source>
                        </external-identifier>
                    </external-identifiers>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.4045709</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0001-8012-6399</uri>
                    <path>0000-0001-8012-6399</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Daniel</given-names>
                        <family-name visibility="public">Lurie</family-name>
                    </personal-details>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.333754</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0002-4387-3819</uri>
                    <path>0000-0002-4387-3819</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Vanessa</given-names>
                        <family-name visibility="public">Sochat</family-name>
                    </personal-details>
                    <external-identifiers visibility="public">
                        <external-identifier>
                            <external-id-common-name>Loop profile</external-id-common-name>
                            <external-id-reference>188284</external-id-reference>
                            <external-id-url>http://loop.frontiersin.org/people/188284/overview?referrer=orcid_profile</external-id-url>
                        </external-identifier>
                        <external-identifier>
                            <external-id-common-name>ResearcherID</external-id-common-name>
                            <external-id-reference>C-6893-2015</external-id-reference>
                            <external-id-url>http://www.researcherid.com/rid/C-6893-2015</external-id-url>
                            <external-id-source>
                                <uri>http://orcid.org/0000-0001-7707-4137</uri>
                                <path>0000-0001-7707-4137</path>
                                <host>orcid.org</host>
                            </external-id-source>
                        </external-identifier>
                        <external-identifier>
                            <external-id-common-name>Scopus Author ID</external-id-common-name>
                            <external-id-reference>56145621000</external-id-reference>
                            <external-id-url>http://www.scopus.com/inward/authorDetails.url?authorID=56145621000&amp;partnerID=MN8TOARS</external-id-url>
                            <external-id-source>
                                <uri>http://orcid.org/0000-0002-5982-8983</uri>
                                <path>0000-0002-5982-8983</path>
                                <host>orcid.org</host>
                            </external-id-source>
                        </external-identifier>
                    </external-identifiers>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.29197392</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0003-3456-2493</uri>
                    <path>0000-0003-3456-2493</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Yaroslav</given-names>
                        <family-name visibility="public">Halchenko</family-name>
                    </personal-details>
                    <researcher-urls visibility="public">
                        <researcher-url>
                            <url-name>Center for Open Neuroscience</url-name>
                            <url>http://centerforopenneuroscience.org</url>
                        </researcher-url>
                        <researcher-url>
                            <url-name>HaxbyLab web page</url-name>
                            <url>http://haxbylab.dartmouth.edu/ppl/yarik.html</url>
                        </researcher-url>
                        <researcher-url>
                            <url-name>Personal</url-name>
                            <url>http://onerussian.com</url>
                        </researcher-url>
                    </researcher-urls>
                    <keywords visibility="public">
                        <keyword>fMRI, MVPA, NeuroDebian, PyMVPA, DataLad</keyword>
                    </keywords>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.29197392</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0003-4010-4632</uri>
                    <path>0000-0003-4010-4632</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Cyril</given-names>
                        <family-name visibility="public">Pernet</family-name>
                        <credit-name visibility="public">Cyril Pernet</credit-name>
                    </personal-details>
                    <biography visibility="public">I have a PhD in Cognitive Neuropsychology from the university of Toulouse III in France where I was working with Dr JF Demonet and Dr P Celsis. I moved next to Finland (Prof R. Salmelin) then Glasgow (Prof B Belin) where I was respectively post-doc fellow and post-doc RA. In 2007 I joined the Brain Research Imaging Center in Edinburgh as fMRI lead for SINAPSE (Scottish Imaging Network A Platform for Scientific Excellence = coordination of some fMRI activities across Scotland). I am now Academic Fellow, teaching fMRI/EEG and researching in the areas of language and categorization with a focus on methods and clinical applications (brain tumours, stroke). </biography>
                    <contact-details>
                        <address>
                            <country visibility="public">GB</country>
                        </address>
                    </contact-details>
                    <external-identifiers visibility="public">
                        <external-identifier>
                            <external-id-common-name>ResearcherID</external-id-common-name>
                            <external-id-reference>A-9237-2008</external-id-reference>
                            <external-id-url>http://www.researcherid.com/rid/A-9237-2008</external-id-url>
                            <external-id-source>
                                <uri>http://orcid.org/0000-0001-7707-4137</uri>
                                <path>0000-0001-7707-4137</path>
                                <host>orcid.org</host>
                            </external-id-source>
                        </external-identifier>
                    </external-identifiers>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.28607485</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0002-8880-9204</uri>
                    <path>0000-0002-8880-9204</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Daniel</given-names>
                        <family-name visibility="public">Margulies</family-name>
                    </personal-details>
                    <researcher-urls visibility="public">
                        <researcher-url>
                            <url-name>lab homepage</url-name>
                            <url>http://www.cbs.mpg.de/independent-research-groups/neuroanatomy-and-connectivity</url>
                        </researcher-url>
                        <researcher-url>
                            <url-name>personal homepage</url-name>
                            <url>http://www.cbs.mpg.de/~margulies</url>
                        </researcher-url>
                    </researcher-urls>
                    <contact-details>
                        <address/>
                    </contact-details>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.26971394</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0002-3982-4416</uri>
                    <path>0000-0002-3982-4416</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Dav</given-names>
                        <family-name visibility="public">Clark</family-name>
                    </personal-details>
                    <researcher-urls visibility="public">
                        <researcher-url>
                            <url-name>Research Updates</url-name>
                            <url>http://bead.glass</url>
                        </researcher-url>
                    </researcher-urls>
                    <contact-details>
                        <address>
                            <country visibility="public">US</country>
                        </address>
                    </contact-details>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.26971394</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0001-9030-2202</uri>
                    <path>0000-0001-9030-2202</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Joke</given-names>
                        <family-name visibility="public">Durnez</family-name>
                    </personal-details>
                    <contact-details>
                        <address>
                            <country visibility="public">US</country>
                        </address>
                    </contact-details>
                    <keywords visibility="public">
                        <keyword>Neuroscience</keyword>
                        <keyword>Statistical Power</keyword>
                        <keyword>Statistics</keyword>
                    </keywords>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.2383957</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0001-6488-4739</uri>
                    <path>0000-0001-6488-4739</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Alexander</given-names>
                        <family-name visibility="public">Schaefer</family-name>
                    </personal-details>
                    <contact-details>
                        <address>
                            <country visibility="public">DE</country>
                        </address>
                    </contact-details>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.2359997</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0002-3939-3003</uri>
                    <path>0000-0002-3939-3003</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Ian</given-names>
                        <family-name visibility="public">Charest</family-name>
                    </personal-details>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
    </orcid-search-results>
</orcid-message>

Exception in thread "Thread-3" java.lang.NullPointerException
    at org.isatools.isacreator.orcid.xmlhandlers.OrcidSearchResultHandler.getOrcidAuthor(OrcidSearchResultHandler.java:81)
    at org.isatools.isacreator.orcid.xmlhandlers.OrcidSearchResultHandler.getOrcidAuthors(OrcidSearchResultHandler.java:51)
    at org.isatools.isacreator.orcid.impl.OrcidClientImpl.processOrcidProfles(OrcidClientImpl.java:114)
    at org.isatools.isacreator.orcid.impl.OrcidClientImpl.getOrcidProfiles(OrcidClientImpl.java:97)
    at org.isatools.isacreator.orcid.gui.OrcidLookupUI$6.run(OrcidLookupUI.java:249)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by agbeltran** [comment]
Thanks for the report. I'm checking in the latest development version (please, note we have a 1.7.8 release too in the releases tab here at Github) and cannot reproduce. Could you please check either with 1.7.8 or the development version?

I tried the same query and got:

`starting search
query string=q=text:gorgolewski
URI=http://pub.orcid.org/search/orcid-bio/?q=text:gorgolewski
status text=OK
contents=<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<orcid-message xmlns="http://www.orcid.org/ns/orcid">
    <message-version>1.1</message-version>
    <orcid-search-results num-found="28">
        <orcid-search-result>
            <relevancy-score>0.6939816</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0003-3321-7583</uri>
                    <path>0000-0003-3321-7583</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Krzysztof</given-names>
                        <family-name visibility="public">Gorgolewski</family-name>
                        <credit-name visibility="public">Krzysztof Jacek Gorgolewski</credit-name>
                        <other-names visibility="public">
                            <other-name>Chris Filo Gorgolewski</other-name>
                        </other-names>
                    </personal-details>
                    <researcher-urls visibility="public">
                        <researcher-url>
                            <url-name>Personal Blog</url-name>
                            <url>http://multiplecomparisons.blogspot.com</url>
                        </researcher-url>
                    </researcher-urls>
                    <contact-details>
                        <address>
                            <country visibility="public">US</country>
                        </address>
                    </contact-details>
                    <keywords visibility="public">
                        <keyword>neuroimaging</keyword>
                        <keyword>neuroinformatics</keyword>
                    </keywords>
                    <external-identifiers visibility="public">
                        <external-identifier>
                            <external-id-common-name>Scopus Author ID</external-id-common-name>
                            <external-id-reference>55355064700</external-id-reference>
                            <external-id-url>http://www.scopus.com/inward/authorDetails.url?authorID=55355064700&amp;partnerID=MN8TOARS</external-id-url>
                            <external-id-source>
                                <uri>http://orcid.org/0000-0002-5982-8983</uri>
                                <path>0000-0002-5982-8983</path>
                                <host>orcid.org</host>
                            </external-id-source>
                        </external-identifier>
                        <external-identifier>
                            <external-id-common-name>Loop profile</external-id-common-name>
                            <external-id-reference>34684</external-id-reference>
                            <external-id-url>http://loop.frontiersin.org/people/34684/overview?referrer=orcid_profile</external-id-url>
                        </external-identifier>
                    </external-identifiers>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.55518526</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0002-6290-553X</uri>
                    <path>0000-0002-6290-553X</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Camille</given-names>
                        <family-name visibility="public">Maumet</family-name>
                    </personal-details>
                    <researcher-urls visibility="public">
                        <researcher-url>
                            <url>http://camillemaumet.com</url>
                        </researcher-url>
                    </researcher-urls>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.45800447</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0002-6558-5113</uri>
                    <path>0000-0002-6558-5113</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Tal</given-names>
                        <family-name visibility="public">Yarkoni</family-name>
                    </personal-details>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.39257526</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0001-8012-6399</uri>
                    <path>0000-0001-8012-6399</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Daniel</given-names>
                        <family-name visibility="public">Lurie</family-name>
                    </personal-details>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.32385808</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0002-4387-3819</uri>
                    <path>0000-0002-4387-3819</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Vanessa</given-names>
                        <family-name visibility="public">Sochat</family-name>
                    </personal-details>
                    <external-identifiers visibility="public">
                        <external-identifier>
                            <external-id-common-name>ResearcherID</external-id-common-name>
                            <external-id-reference>C-6893-2015</external-id-reference>
                            <external-id-url>http://www.researcherid.com/rid/C-6893-2015</external-id-url>
                            <external-id-source>
                                <uri>http://orcid.org/0000-0001-7707-4137</uri>
                                <path>0000-0001-7707-4137</path>
                                <host>orcid.org</host>
                            </external-id-source>
                        </external-identifier>
                        <external-identifier>
                            <external-id-common-name>Scopus Author ID</external-id-common-name>
                            <external-id-reference>56145621000</external-id-reference>
                            <external-id-url>http://www.scopus.com/inward/authorDetails.url?authorID=56145621000&amp;partnerID=MN8TOARS</external-id-url>
                            <external-id-source>
                                <uri>http://orcid.org/0000-0002-5982-8983</uri>
                                <path>0000-0002-5982-8983</path>
                                <host>orcid.org</host>
                            </external-id-source>
                        </external-identifier>
                        <external-identifier>
                            <external-id-common-name>Loop profile</external-id-common-name>
                            <external-id-reference>188284</external-id-reference>
                            <external-id-url>http://loop.frontiersin.org/people/188284/overview?referrer=orcid_profile</external-id-url>
                        </external-identifier>
                    </external-identifiers>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.2833168</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0003-3456-2493</uri>
                    <path>0000-0003-3456-2493</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Yaroslav</given-names>
                        <family-name visibility="public">Halchenko</family-name>
                    </personal-details>
                    <researcher-urls visibility="public">
                        <researcher-url>
                            <url-name>Center for Open Neuroscience</url-name>
                            <url>http://centerforopenneuroscience.org</url>
                        </researcher-url>
                        <researcher-url>
                            <url-name>HaxbyLab web page</url-name>
                            <url>http://haxbylab.dartmouth.edu/ppl/yarik.html</url>
                        </researcher-url>
                        <researcher-url>
                            <url-name>Personal</url-name>
                            <url>http://onerussian.com</url>
                        </researcher-url>
                    </researcher-urls>
                    <keywords visibility="public">
                        <keyword>fMRI, MVPA, NeuroDebian, PyMVPA, DataLad</keyword>
                    </keywords>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.2833168</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0003-4010-4632</uri>
                    <path>0000-0003-4010-4632</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Cyril</given-names>
                        <family-name visibility="public">Pernet</family-name>
                        <credit-name visibility="public">Cyril Pernet</credit-name>
                    </personal-details>
                    <biography visibility="public">I have a PhD in Cognitive Neuropsychology from the university of Toulouse III in France where I was working with Dr JF Demonet and Dr P Celsis. I moved next to Finland (Prof R. Salmelin) then Glasgow (Prof B Belin) where I was respectively post-doc fellow and post-doc RA. In 2007 I joined the Brain Research Imaging Center in Edinburgh as fMRI lead for SINAPSE (Scottish Imaging Network A Platform for Scientific Excellence = coordination of some fMRI activities across Scotland). I am now Academic Fellow, teaching fMRI/EEG and researching in the areas of language and categorization with a focus on methods and clinical applications (brain tumours, stroke). </biography>
                    <contact-details>
                        <address>
                            <country visibility="public">GB</country>
                        </address>
                    </contact-details>
                    <external-identifiers visibility="public">
                        <external-identifier>
                            <external-id-common-name>ResearcherID</external-id-common-name>
                            <external-id-reference>A-9237-2008</external-id-reference>
                            <external-id-url>http://www.researcherid.com/rid/A-9237-2008</external-id-url>
                            <external-id-source>
                                <uri>http://orcid.org/0000-0001-7707-4137</uri>
                                <path>0000-0001-7707-4137</path>
                                <host>orcid.org</host>
                            </external-id-source>
                        </external-identifier>
                    </external-identifiers>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.27759263</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0002-8880-9204</uri>
                    <path>0000-0002-8880-9204</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Daniel</given-names>
                        <family-name visibility="public">Margulies</family-name>
                    </personal-details>
                    <researcher-urls visibility="public">
                        <researcher-url>
                            <url-name>lab homepage</url-name>
                            <url>http://www.cbs.mpg.de/independent-research-groups/neuroanatomy-and-connectivity</url>
                        </researcher-url>
                        <researcher-url>
                            <url-name>personal homepage</url-name>
                            <url>http://www.cbs.mpg.de/~margulies</url>
                        </researcher-url>
                    </researcher-urls>
                    <external-identifiers visibility="public">
                        <external-identifier>
                            <external-id-common-name>ResearcherID</external-id-common-name>
                            <external-id-reference>L-4719-2016</external-id-reference>
                            <external-id-url>http://www.researcherid.com/rid/L-4719-2016</external-id-url>
                            <external-id-source>
                                <uri>http://orcid.org/0000-0003-1377-5676</uri>
                                <path>0000-0003-1377-5676</path>
                                <host>orcid.org</host>
                            </external-id-source>
                        </external-identifier>
                    </external-identifiers>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.26171684</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0002-3982-4416</uri>
                    <path>0000-0002-3982-4416</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Dav</given-names>
                        <family-name visibility="public">Clark</family-name>
                    </personal-details>
                    <researcher-urls visibility="public">
                        <researcher-url>
                            <url-name>Research Updates</url-name>
                            <url>http://bead.glass</url>
                        </researcher-url>
                    </researcher-urls>
                    <contact-details>
                        <address>
                            <country visibility="public">US</country>
                        </address>
                    </contact-details>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
        <orcid-search-result>
            <relevancy-score>0.26171684</relevancy-score>
            <orcid-profile>
                <orcid-identifier>
                    <uri>http://orcid.org/0000-0001-9030-2202</uri>
                    <path>0000-0001-9030-2202</path>
                    <host>orcid.org</host>
                </orcid-identifier>
                <orcid-bio>
                    <personal-details>
                        <given-names visibility="public">Joke</given-names>
                        <family-name visibility="public">Durnez</family-name>
                    </personal-details>
                    <contact-details>
                        <address>
                            <country visibility="public">US</country>
                        </address>
                    </contact-details>
                    <keywords visibility="public">
                        <keyword>Neuroscience</keyword>
                        <keyword>Statistical Power</keyword>
                        <keyword>Statistics</keyword>
                    </keywords>
                </orcid-bio>
                <orcid-activities/>
            </orcid-profile>
        </orcid-search-result>
    </orcid-search-results>
</orcid-message>

Selected surname =Gorgolewski
Selected author=Krzysztof Gorgolewski
property change new value - contact=Krzysztof Gorgolewski
property change new value - contact=Krzysztof Gorgolewski`
