### ISSUE TITLE
Can't run ISACreator 1.7.7 on Ubuntu 15.04

### ISSUE THREAD

**Issue by drj11** [ISA-tools/ISAcreator#305]
I followed the instructions here http://isacreator.readthedocs.io/en/latest/getting_started.html but I was unable to get ISACreator running.

Here's my OS and Java version:

```
drj@mus:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
drj@mus:~$ java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

When I try and launch the jar file I get an exception:
```
drj@mus:~$ java -jar -Xms256m -Xmx1024m '/home/drj/Downloads/ISAcreator-1.7.7/ISAcreator.jar' 
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
	at java.awt.Window.<init>(Window.java:535)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:174)
	at org.isatools.isacreator.gui.modeselection.ModeSelector.<init>(ModeSelector.java:77)
	at org.isatools.isacreator.launch.ISAcreatorApplication.main(ISAcreatorApplication.java:52)
```

I searched the issue tracker (for `install`) and couldn't find anything applicable, so I created this issue.

**Comment by eamonnmag** [comment]
You need to install the JRE
```sudo apt-get install openjdk-6-jre```

**Comment by drj11** [comment]
Thanks for responding.

[The documentation](http://isacreator.readthedocs.io/en/latest/getting_started.html) says: "(if your Java version is above 1.6, all is well)".

Is that wrong then? Only Java 1.6.something will do, and Java 1.7.something is simply no good?

**Comment by drj11** [comment]
So, a little more digging reveals that my problem wasn't 1.6 versus 1.7, but headless versus not-headless. I had the headless JRE installed and that's not sufficient.

Before the fix:
```
$ apt list --installed 'openjdk*'
Listing... Done
openjdk-7-jre-headless/vivid-updates,now 7u95-2.6.4-0ubuntu0.15.04.1 amd64 [installed,automatic]
```

Installing the "full" (as opposed to headless) JRE fixes the problem.

```
sudo apt-get install openjdk-7-jre
```

Fixed.

**Comment by eamonnmag** [comment]
Great! Thanks for getting back so quickly. And apologies for the delay in responding to your issue.
