### ISSUE TITLE
Mapping Component: define mapping add/remove buttons are broken

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/ISAcreator#307]
![image](https://cloud.githubusercontent.com/assets/517736/16833000/0d482478-49a5-11e6-8949-0563a83f42df.png)

ISAcreator-1.7.8
MacOs: el capitan
Java 8

(java 8 could be the cause of these issues: running more tests with older java versions)

/Users/Philippe/prs/Documents/TESTING/ISAcreator-1.7.8-all/profiles.sup
User profiles loaded, we have 1
org.isatools.isacreator.plugins.DefaultPluginMenu@1ecfe148
javax.swing.JMenu[,5,0,0x0,hidden,alignmentX=0.0,alignmentY=0.0,border=com.apple.laf.AquaMenuBorder@edae259,flags=264,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=javax.swing.plaf.InsetsUIResource[top=0,left=0,bottom=0,right=0],paintBorder=false,paintFocus=false,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=plugins]
Loaded configuration
============Hiding glass pane
removing current page...
Hopefully it isn't present: true

**Comment by proccaserra** [comment]
similar issue shows up when using Java 6 and Java 7.
However, the buttons add/remove work when used with Protocol REF to specify Performer or Date.

must be minor
![image](https://cloud.githubusercontent.com/assets/517736/16833969/94b8cd82-49a9-11e6-91ca-8a5af7289df4.png)

**Comment by djcomlab** [comment]
Can't replicate in latest build off latest development branch, in either Windows or Mac OSX so seems to be OK now after a rebuild; related to #311
