### ISSUE TITLE
Compile time error in CiteExploreClient.java

### ISSUE THREAD

**Issue by Kabenla** [ISA-tools/ISAcreator#310]
On the re develop branch, there is a compile time error in ISAcreator/src/main/java/org/isatools/isacreator/publicationlocator/CiteExploreClient.java at the public List<CiteExploreResult> performQuery function.  The call to searchPublications does not follow the method signature from the class generated by the wsdl.

Should be something like 
ResponseWrapper responseWrapper = port.searchPublications(fullQueryString, "core", "*", "25", "desc", false, "isatools@googlgroups.com");

Instead of 

 ResponseWrapper responseWrapper = port.searchPublications(fullQueryString, "core", 0, "", false, "isatools@googlgroups.com");

**Comment by agbeltran** [comment]
Thanks for the report - this was fixed in commit 2c4779b04b7c4d8798b4bb920f3805da99786841
