### ISSUE TITLE
Various panes in UI get mangled when creating new study

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/ISAcreator#311]
Various panes in UI get mangled on Mac OSX (Sierra) running ISAcreator 1.7.8 when creating new study.

![screen shot 2017-01-18 at 12 29 52](https://cloud.githubusercontent.com/assets/3604134/22064125/1044a23c-dd7a-11e6-90d7-612dfa4cc2f7.png)
![screen shot 2017-01-18 at 12 30 02](https://cloud.githubusercontent.com/assets/3604134/22064126/10452b30-dd7a-11e6-962c-32b4e9f0477f.png)
![screen shot 2017-01-18 at 12 30 13](https://cloud.githubusercontent.com/assets/3604134/22064127/10465852-dd7a-11e6-8987-f864d385b8ea.png)

Seems to be related to #306

**Comment by agbeltran** [comment]
This is when building with Java 1.7 right?

**Comment by djcomlab** [comment]
No, this is with the ISAcreator 1.7.8 build.

**Comment by agbeltran** [comment]
thanks, my question was about the Java version

**Comment by djcomlab** [comment]
Sure, the ISAcreator 1.7.8 release is built on Java 1.6 as far as I understand.

**Comment by agbeltran** [comment]
After further clarifications, this issue appears in the ISAcreator 1.7.8-mixs prerelease available in the releases: https://github.com/ISA-tools/ISAcreator/releases

**Comment by djcomlab** [comment]
Can't replicate in latest build off latest development branch, in either Windows or Mac OSX so seems to be OK now after a rebuild; related to #307
