### ISSUE TITLE
Issues with ISAcreator 1.7.9; with Java8u101

### ISSUE THREAD

**Issue by Vivlj** [ISA-tools/ISAcreator#316]
We're working for Win Hide at SITraN at the University of Sheffield and are working directly with Philippe.
During a telephone conference last Tuesday he told us to report issues directly to the GitHub site, hence the queries here.
We've encountered a number of issues with ISAcreator 1.7.9 with Java 8u101 (I installed this older Java as it didn't work at all with the later u121 version).

Issue 1
Mapping tool with ISAcreator will not load file to be mapped. Says filenames must not contain special characters. No special characteristics are present

Issue 2: Saved to desktop however can’t reload it in ISAcreator as is not listed and no i, s, a files created. 

I look forward to hearing back from you.
With many thanks,
Viv
Scientific Data Curator

**Comment by agbeltran** [comment]
Hi @Vivlj - thanks for your message. 

Issue 1
Are you able to share with us the file you are using for the mapper? If not here, you can email us to our internal (only the ISA team) mailing list: isatools@googlegroups.com

Issue 2
can you please describe what files you saved and the steps you followed?

Thanks

**Comment by djcomlab** [comment]
Hi @Vivlj thanks for the issue report and also for sending the xls file direct to us via email.

I am trying to replicate the issues you experienced. Can you please confirm if you are using Windows, Mac OS or Linux, and which version of the OS?

I am using Mac OSX Sierra. For issue 1 I am unable to replicate the issue that you have described - if I open the mapper, select the `GTC-GSE19332.xls` file and click "Select for mapping" and press the "next" button, it proceeds without error.

For issue 2 you mentioned you tried to save input from PubMedID, but I'm not sure I understand how the steps you are following in this scenario. If you could list exactly the steps you are having trouble with (e.g. 1. Open "create new experiment description", 2. Open "map from existing file" etc.) or provide a screenshot of where you are at when you are experiencing the problem, then this would help us greatly in determining and solving the problem for you.

Thanks!

**Comment by djcomlab** [comment]
Hi @Vivlj I noticed when trying to load the file you sent, I get an error loading it and have filed an issue #317 accordingly. I'm not sure if this was related to any of the issues you experienced detailed above.

**Comment by djcomlab** [comment]
Fixed in development branch, fix will be pushed out in next release.
