### ISSUE TITLE
Directory paths in "Array Data File" Field (Windows; ISAcreator 1.7.9; Java8u101)

### ISSUE THREAD

**Issue by Vivlj** [ISA-tools/ISAcreator#318]
Hi

I have a recurring problem where the directory path, added to the Array Data File filed.
I the data files by double clicking the box in the column. I then double click on the file I want to add and then click Select File button.
Upon doing this I get the following path format added to the corresponding box:
 e.g. C:\Users\VivJ\Desktop\FilesUpload\Table1_1.CEL

I save after every addition.
However after exiting ISAcreator e.g. in the evening and reload, say later or the next day, the backslashes within the path are no longer there.

I have tried this on a number of occasions all with the same result.

Any help with this would be greatly appreciated.
With many thanks
Viv

**Comment by proccaserra** [comment]
Hi Viv,

Thank you for reporting. Just to be sure, when reloading the following day
, is it only a display issues or is it that, when saving, the tools loses
the file path?

(this is on windows 10, right?)

Kind regards

Philippe

**Comment by Vivlj** [comment]
Hi Philippe,

Thanks so much for getting back to me.

It is when saving that the tool loses the directory path.
Yes, I'm on Windows 10

Best wishes,
Viv

**Comment by djcomlab** [comment]
Bug is same as reported in #245

**Comment by djcomlab** [comment]
Fix pushed to development branch, will be available in upcoming release of ISAcreator 1.7.10.
