### ISSUE TITLE
'ISArchive has not been created! Check the log file'

### ISSUE THREAD

**Issue by yeodynasty** [ISA-tools/ISAcreator#320]
Hi, after validation, I can't archive my data properly. 
The archive file is corrupted, and I have an error, as outlined in the image attached.
Although it asks to check the log file, but I can't find it anywhere in the folder.
Kindly assist, as it is urgent.

Sincerely, Hock Chuan

![image](https://user-images.githubusercontent.com/1333150/28396398-c1b18632-6d2d-11e7-8584-9a04dffc763e.png)

**Comment by proccaserra** [comment]
Hi Hock
Thx for reporting. could you tell us which version of ISAcreator you are currently running as well as information about your environment (apparently windows10, but which java version)
Also, I was wondering about the size of the your input dataset. 
Does ISAcreator fail to create an archive at all (as indicated by the error message) or does it create a corrupt zip file. If the latter, what is the size of the generated archive?

If you urgently need archiving as zip and if ISAcreator fails, you may resort to using compressing tools directly available to you on windows and then uploading to EMBL-EBI Metabolights 

Let us know

best regards

Philippe

**Comment by yeodynasty** [comment]
Hi Philippe. From my investigation, the issue is due to a limitation in the size of the download folder in the windows environment. The resulting archive file is corrupt.

It now archives properly after I move to another folder. My files are not particularly big, about 16 gig. Apparently there is nothing wrong with my java.
Thank you for your prompt reply. :)

Sent from Yahoo Mail for iPhone


On Thursday, July 20, 2017, 6:53 PM, Philippe Rocca-Serra <notifications@github.com> wrote:


Hi Hock
Thx for reporting. could you tell us which version of ISAcreator you are currently running as well as information about your environment (apparently windows10, but which java version)
Also, I was wondering about the size of the your input dataset.
Does ISAcreator fail to create an archive at all (as indicated by the error message) or does it create a corrupt zip file. If the latter, what is the size of the generated archive?

If you urgently need archiving as zip and if ISAcreator fails, you may resort to using compressing tools directly available to you on windows and then uploading to EMBL-EBI Metabolights

Let us know

best regards

Philippe

**Comment by agbeltran** [comment]
Great that this is solved! Closing the issue.
