### ISSUE TITLE
1.7.10 fails to run in Java 8

### ISSUE THREAD

**Issue by DanBerrios** [ISA-tools/ISAcreator#330]
I have the latest Java 8 installed... 
After starting ISACreator, I get an ISACreator splash page (!) that says unable to run ISACreator using this version of Java.

? ..but I have the latest java....

**Comment by agbeltran** [comment]
@DanBerrios Please use release 1.7.11 (https://github.com/ISA-tools/ISAcreator/releases) or the development version, which work in Java 8
