### ISSUE TITLE
DOI and PMID search not working 

### ISSUE THREAD

**Issue by khaug** [ISA-tools/ISAcreator#331]
When searching for a publication using DOI or PMID, you can not "trigger" the search form. Nothing seems to happen, including no log output. Any ideas?

**Comment by proccaserra** [comment]
another change to UKPubmed API ? we usually receive a notification .
Digging around picked up the following:

https://groups.google.com/a/ebi.ac.uk/forum/#!topic/epmc-webservices/XwDROL5Aa60

**Comment by agbeltran** [comment]
This was fixed in 6b2ed7621e713621c6da3546ba8097ee0c302578
