### ISSUE TITLE
Errors in isatab files test-data

### ISSUE THREAD

**Issue by mverouden** [ISA-tools/ISAcreator#332]
Within [ISAcreator-1.7.11-all.zip](https://github.com/ISA-tools/ISAcreator/releases/download/v1.7.11/ISAcreator-1.7.11-all.zip) an example is contained for the investigation BII-I-1. This example is rather erroneous. The Investigation Person Last Name of contacts 2 and 3 have been switched. The same holds for the study contact of study both studies.

Kind regards,

**Comment by agbeltran** [comment]
Thanks @mverouden - this will be fixed from now on.
